"""Valanga dynamics adapter for Morpion Solitaire (5T / 5D)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, cast

import valanga

from .canonical import Move
from .state import Dir, MorpionState, Point, Segment, Variant, norm_seg

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator, Sequence

DIRECTIONS: tuple[Dir, ...] = (
    (1, 0),
    (0, 1),
    (1, 1),
    (1, -1),
)

Action = tuple[int, int, int, int]


class MorpionIllegalActionError(ValueError):
    """Raised when an action violates Morpion rules."""

    @classmethod
    def missing_point_already_present(cls) -> MorpionIllegalActionError:
        """Create error for adding an already occupied missing point."""
        return cls("Illegal action: missing point already present.")

    @classmethod
    def line_missing_more_than_one_point(cls) -> MorpionIllegalActionError:
        """Create error for a line missing more than one required point."""
        return cls("Illegal action: line missing more than one point.")

    @classmethod
    def overlaps_existing_segment(cls) -> MorpionIllegalActionError:
        """Create error for segment overlap with an existing line."""
        return cls("Illegal action: overlaps existing segment.")

    @classmethod
    def violates_same_direction_rule(cls) -> MorpionIllegalActionError:
        """Create error for same-direction incompatibility under variant rules."""
        return cls("Illegal action: violates 5T/5D same-direction rule.")

    @classmethod
    def action_out_of_range(cls) -> MorpionIllegalActionError:
        """Create error for action index values outside valid bounds."""
        return cls("Morpion action out of range.")


class MorpionActionNameError(ValueError):
    """Raised when parsing a textual action representation fails."""

    def __init__(self, name: str) -> None:
        """Build parse error with original action name."""
        super().__init__(f"Bad action name: {name!r}")


class MorpionActionTypeError(TypeError):
    """Raised when action key is not a valid Morpion action tuple."""

    def __init__(self) -> None:
        """Build tuple-shape validation error."""
        super().__init__(
            "Morpion actions must be 4-tuples: (dir_index, x0, y0, missing_i)."
        )


def _as_action(action: valanga.BranchKey) -> Action:
    """Validate and cast a generic branch key to Morpion ``Action``."""
    if not isinstance(action, tuple):
        raise MorpionActionTypeError
    action_tuple = cast("tuple[object, ...]", action)
    if len(action_tuple) != 4:
        raise MorpionActionTypeError

    normalized = cast("Action", action_tuple)
    dir_index, _, _, missing_i = normalized
    if dir_index not in range(4) or missing_i not in range(5):
        raise MorpionIllegalActionError.action_out_of_range()
    return normalized


class _ListBranchKeyGen(valanga.BranchKeyGeneratorP[valanga.BranchKey]):
    """Small resettable in-memory branch-key generator."""

    sort_branch_keys: bool = False

    def __init__(
        self,
        keys: Sequence[valanga.BranchKey],
        *,
        sort_branch_keys: bool = False,
    ) -> None:
        """Store keys for deterministic iteration."""
        self.sort_branch_keys = sort_branch_keys
        self._keys = sorted(keys, key=repr) if self.sort_branch_keys else list(keys)
        self._i = 0

    @property
    def all_generated_keys(self) -> Sequence[valanga.BranchKey] | None:
        """Return all keys already generated by this instance."""
        return self._keys

    def __iter__(self) -> Iterator[valanga.BranchKey]:
        """Return iterator protocol self."""
        return self

    def __next__(self) -> valanga.BranchKey:
        """Return next key or raise ``StopIteration``."""
        if self._i >= len(self._keys):
            raise StopIteration
        key = self._keys[self._i]
        self._i += 1
        return key

    def more_than_one(self) -> bool:
        """Return whether more than one branch key exists."""
        return len(self._keys) > 1

    def get_all(self) -> Sequence[valanga.BranchKey]:
        """Return all branch keys as a new list."""
        return list(self._keys)

    def copy_with_reset(self) -> _ListBranchKeyGen:
        """Return a fresh generator reset at position zero."""
        return _ListBranchKeyGen(self._keys, sort_branch_keys=self.sort_branch_keys)


def _line_points(
    x0: int, y0: int, direction: Dir
) -> tuple[Point, Point, Point, Point, Point]:
    """Return the five points on the candidate line."""
    dx, dy = direction
    return (
        (x0 + 0 * dx, y0 + 0 * dy),
        (x0 + 1 * dx, y0 + 1 * dy),
        (x0 + 2 * dx, y0 + 2 * dy),
        (x0 + 3 * dx, y0 + 3 * dy),
        (x0 + 4 * dx, y0 + 4 * dy),
    )


def _unit_segments_on_line(
    pts5: tuple[Point, Point, Point, Point, Point],
) -> tuple[Segment, Segment, Segment, Segment]:
    """Return the four unit segments composing a five-point line."""
    return (
        norm_seg(pts5[0], pts5[1]),
        norm_seg(pts5[1], pts5[2]),
        norm_seg(pts5[2], pts5[3]),
        norm_seg(pts5[3], pts5[4]),
    )


def action_to_played_move(action: valanga.BranchKey) -> Move:
    """Convert one Morpion action to its played-line endpoint representation."""
    dir_index, x0, y0, _ = _as_action(action)
    pts5 = _line_points(x0, y0, DIRECTIONS[dir_index])
    start = pts5[0]
    end = pts5[4]
    if start <= end:
        return (start[0], start[1], end[0], end[1])
    return (end[0], end[1], start[0], start[1])


def _point_usage_kind(index: int) -> int:
    """Return usage kind bitmask for line point index."""
    return 1 if index in (0, 4) else 2


def _is_parallel_compat(
    state: MorpionState,
    dir_index: int,
    pts5: tuple[Point, Point, Point, Point, Point],
) -> bool:
    """Return whether same-direction sharing is valid under 5T/5D rules."""
    if state.variant == Variant.DISJOINT_5D:
        return all((p, dir_index) not in state.dir_usage for p in pts5)

    for index, point in enumerate(pts5):
        want = _point_usage_kind(index)
        have = state.dir_usage.get((point, dir_index), 0)
        if have == 0:
            continue
        if have & 2:
            return False
        if have & 1 and want != 1:
            return False
    return True


def _apply_dir_usage(
    state: MorpionState,
    dir_index: int,
    pts5: tuple[Point, Point, Point, Point, Point],
) -> dict[tuple[Point, int], int]:
    """Return updated same-direction point-usage map after adding one line."""
    new_usage = dict(state.dir_usage)
    for index, point in enumerate(pts5):
        kind = _point_usage_kind(index)
        key = (point, dir_index)
        new_usage[key] = new_usage.get(key, 0) | kind
    return new_usage


def _missing_index_for_candidate(
    points: frozenset[Point],
    pts5: tuple[Point, Point, Point, Point, Point],
) -> int | None:
    """Return missing index when exactly one point is absent, else ``None``."""
    missing = [index for index, point in enumerate(pts5) if point not in points]
    if len(missing) != 1:
        return None
    return missing[0]


@dataclass(slots=True)
class MorpionDynamics(valanga.Dynamics[MorpionState]):
    """Rule engine for Morpion transitions."""

    def legal_actions(
        self,
        state: MorpionState,
    ) -> valanga.BranchKeyGeneratorP[valanga.BranchKey]:
        """Return legal action keys for ``state``."""
        actions = list(self._enumerate_actions(state))
        return _ListBranchKeyGen(actions, sort_branch_keys=True)

    def step(
        self,
        state: MorpionState,
        action: valanga.BranchKey,
    ) -> valanga.Transition[MorpionState]:
        """Apply a legal move and return transition metadata."""
        dir_index, x0, y0, missing_i = self._as_action(action)
        pts5 = _line_points(x0, y0, DIRECTIONS[dir_index])

        new_point = pts5[missing_i]
        if new_point in state.points:
            raise MorpionIllegalActionError.missing_point_already_present()

        for index, point in enumerate(pts5):
            if index == missing_i:
                continue
            if point not in state.points:
                raise MorpionIllegalActionError.line_missing_more_than_one_point()

        segs = _unit_segments_on_line(pts5)
        if any(seg in state.used_unit_segments for seg in segs):
            raise MorpionIllegalActionError.overlaps_existing_segment()

        if not _is_parallel_compat(state, dir_index, pts5):
            raise MorpionIllegalActionError.violates_same_direction_rule()

        new_points = set(state.points)
        new_points.add(new_point)

        new_segs = set(state.used_unit_segments)
        new_segs.update(segs)

        next_played_moves = set(state.played_moves)
        next_played_moves.add(action_to_played_move(action))

        next_state = MorpionState(
            points=frozenset(new_points),
            used_unit_segments=frozenset(new_segs),
            dir_usage=_apply_dir_usage(state, dir_index, pts5),
            played_moves=frozenset(next_played_moves),
            moves=state.moves + 1,
            variant=state.variant,
        )

        is_over = not any(self._enumerate_actions(next_state, stop_after_one=True))
        return valanga.Transition(
            next_state=next_state,
            modifications=None,
            is_over=is_over,
            over_event=None,
            info={"action": self.action_name(state, action)},
        )

    def action_name(self, state: MorpionState, action: valanga.BranchKey) -> str:
        """Convert an action key to a deterministic text representation."""
        _ = state
        dir_index, x0, y0, missing_i = self._as_action(action)
        dx, dy = DIRECTIONS[dir_index]
        return f"d={dx},{dy}; start=({x0},{y0}); missing={missing_i}"

    def action_from_name(self, state: MorpionState, name: str) -> valanga.BranchKey:
        """Parse action text produced by :meth:`action_name`."""
        _ = state
        parts = [part.strip() for part in name.split(";")]
        if len(parts) != 3:
            raise MorpionActionNameError(name)

        d_part = parts[0].removeprefix("d=").strip()
        start_part = parts[1].removeprefix("start=").strip()
        miss_part = parts[2].removeprefix("missing=").strip()

        dx_s, dy_s = [value.strip() for value in d_part.split(",")]
        dx, dy = int(dx_s), int(dy_s)

        start_part = start_part.removeprefix("(").removesuffix(")")
        x0_s, y0_s = [value.strip() for value in start_part.split(",")]
        x0, y0 = int(x0_s), int(y0_s)

        missing_i = int(miss_part)
        return (DIRECTIONS.index((dx, dy)), x0, y0, missing_i)

    @staticmethod
    def _as_action(action: valanga.BranchKey) -> Action:
        """Validate and cast a generic branch key to Morpion ``Action``."""
        return _as_action(action)

    def _enumerate_actions(
        self,
        state: MorpionState,
        *,
        stop_after_one: bool = False,
    ) -> Iterable[Action]:
        """Enumerate legal actions by scanning a bounded lattice box."""
        if not state.points:
            return

        xs = [p[0] for p in state.points]
        ys = [p[1] for p in state.points]
        margin = 4
        minx, maxx = min(xs) - margin, max(xs) + margin
        miny, maxy = min(ys) - margin, max(ys) + margin

        for dir_index, direction in enumerate(DIRECTIONS):
            for x0 in range(minx, maxx + 1):
                for y0 in range(miny, maxy + 1):
                    pts5 = _line_points(x0, y0, direction)

                    missing_i = _missing_index_for_candidate(state.points, pts5)
                    if missing_i is None:
                        continue

                    segs = _unit_segments_on_line(pts5)
                    if any(seg in state.used_unit_segments for seg in segs):
                        continue

                    if not _is_parallel_compat(state, dir_index, pts5):
                        continue

                    yield (dir_index, x0, y0, missing_i)
                    if stop_after_one:
                        return
